import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';
const c=document.querySelector('#scene'),r=new THREE.WebGLRenderer({canvas:c,antialias:true});r.setPixelRatio(Math.min(2,devicePixelRatio));r.shadowMap.enabled=true;
const s=new THREE.Scene(),cam=new THREE.PerspectiveCamera(39,1,.1,100),clock=new THREE.Clock(),island=new THREE.Group(),sky=new THREE.Group();s.add(island,sky);cam.position.set(10,6.5,12);
const hemi=new THREE.HemisphereLight(0xffdec2,0x372348,2.4),key=new THREE.DirectionalLight(0xffe1ba,3);key.position.set(6,9,4);key.castShadow=true;s.add(hemi,key);
const toon=(color,glow=0)=>new THREE.MeshToonMaterial({color,emissive:color,emissiveIntensity:glow});const add=(g,m,x=0,y=0,z=0,parent=island)=>{const q=new THREE.Mesh(g,m);q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;parent.add(q);return q};
class FloatingIsland{constructor(){add(new THREE.CylinderGeometry(5.1,3.15,1.8,9),toon(0x85503e),0,-1,0);add(new THREE.CylinderGeometry(5.15,4.85,.38,9),toon(0x6eaa66),0,-.05,0);for(let i=0;i<15;i++){let a=i/15*Math.PI*2;add(new THREE.DodecahedronGeometry(.15+Math.random()*.18),toon(0x744a42),Math.cos(a)*(3.8+Math.random()),.32,Math.sin(a)*(3.8+Math.random()))}}update(t){island.position.y=Math.sin(t*.9)*.16}}
class TokyoTower{constructor(){this.glow=[];const red=toon(0xe94c42),white=toon(0xffe5c8);for(let y=0;y<4;y++){const tier=add(new THREE.CylinderGeometry(.18+y*.095,.28+y*.12,.88,4),y%2?white:red,0,.7+y*.78,0);tier.rotation.y=Math.PI/4}add(new THREE.ConeGeometry(.12,1.8,4),red,0,4.65,0).rotation.y=Math.PI/4;for(let y=1;y<4;y++){const lamp=add(new THREE.SphereGeometry(.075,8,6),toon(0xffc558),.28+y*.07,.65+y*.78,.28);this.glow.push(lamp.material)}}setNight(n){this.glow.forEach(m=>m.emissiveIntensity=n?1.8:0)}}
class Torii{constructor(){this.glow=[];const red=toon(0xc93e37);for(const x of [-1,1])add(new THREE.CylinderGeometry(.11,.15,1.5,8),red,x,.9,2.7);add(new THREE.BoxGeometry(2.5,.18,.18),red,0,1.65,2.7);add(new THREE.BoxGeometry(2.85,.16,.25),toon(0xf15c4c),0,1.91,2.7);const l=add(new THREE.SphereGeometry(.1,8,6),toon(0xffcc65),0,1.55,2.59);this.glow.push(l.material)}setNight(n){this.glow.forEach(m=>m.emissiveIntensity=n?1.5:0)}}
class FujiTemple{constructor(){this.glow=[];const mountain=add(new THREE.ConeGeometry(1.65,2.3,24),toon(0x6576a4),-3,.85,.8);const cap=add(new THREE.ConeGeometry(.66,.35,24),toon(0xf5f4ef),-3,2.1,.8);cap.rotation.z=Math.PI;add(new THREE.BoxGeometry(1.5,.65,.9),toon(0xd8af7d),2.75,.7,-1.4);const roof=add(new THREE.ConeGeometry(1.18,.65,4),toon(0x334e75),2.75,1.3,-1.4);roof.rotation.y=Math.PI/4;const l=add(new THREE.SphereGeometry(.12,8,6),toon(0xffd26a),2.75,.78,-.9);this.glow.push(l.material)}setNight(n){this.glow.forEach(m=>m.emissiveIntensity=n?1.5:0)}}
class MaplePool{constructor(){this.items=[];const geo=new THREE.PlaneGeometry(.18,.18);for(let i=0;i<260;i++){let m=new THREE.Mesh(geo,toon(i%3?0xea6345:0xf0a438));m.userData={speed:.55+Math.random()*1.1,phase:Math.random()*8};island.add(m);this.reset(m,true);this.items.push(m)}}reset(m,initial=false){m.position.set((Math.random()-.5)*14,initial?Math.random()*7-1:3.7+Math.random()*5,(Math.random()-.5)*13);m.rotation.set(Math.random()*6,Math.random()*6,Math.random()*6)}update(dt,t){this.items.forEach(m=>{m.position.y-=m.userData.speed*dt;m.position.x+=Math.sin(t*1.7+m.userData.phase)*dt*.42;m.rotation.x+=dt*3;m.rotation.z+=dt*1.6;if(m.position.y<-2.35)this.reset(m)})}}
new FloatingIsland();const tower=new TokyoTower(),torii=new Torii(),fuji=new FujiTemple(),leaves=new MaplePool();
// temple lantern path and clouds, intentionally basic geometry only
for(let i=0;i<7;i++){let a=i/7*Math.PI*2;add(new THREE.CylinderGeometry(.06,.09,.55,7),toon(0x704235),Math.cos(a)*3.9,.7,Math.sin(a)*3.9);add(new THREE.SphereGeometry(.22,8,6),toon(0x71bb78),Math.cos(a)*3.9,1.14,Math.sin(a)*3.9)}
const sun=add(new THREE.SphereGeometry(.52,16,12),toon(0xffd46f,1),0,0,0,sky),moon=add(new THREE.SphereGeometry(.38,16,12),toon(0xc8ddff,1),0,0,0,sky);let yaw=.55,pressed=false,oldX=0,boost=1;c.addEventListener('pointerdown',e=>{pressed=true;oldX=e.clientX;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(pressed){yaw-=(e.clientX-oldX)*.01;oldX=e.clientX}});c.addEventListener('pointerup',()=>pressed=false);document.querySelector('#fast').onclick=()=>boost=boost===1?4:1;
function size(){r.setSize(innerWidth,innerHeight,false);cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix()}addEventListener('resize',size);size();
function frame(){let dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime*boost;requestAnimationFrame(frame);const phase=(t%15)/15,day=(Math.sin(phase*Math.PI*2-Math.PI/2)+1)/2,night=1-day;const bg=new THREE.Color().setHSL(.59-.53*day,.58,.16+.55*day);s.background=bg;s.fog=new THREE.FogExp2(bg,.018+night*.028);sun.position.set(Math.cos(phase*Math.PI*2)*8,Math.sin(phase*Math.PI*2)*6,0);moon.position.copy(sun.position).multiplyScalar(-1);sun.visible=day>.1;moon.visible=day<.75;hemi.intensity=.35+day*2.2;key.intensity=.1+day*3.1;key.color.setHSL(.1,.7,.48+day*.32);let on=day<.34;tower.setNight(on);torii.setNight(on);fuji.setNight(on);document.querySelector('#time').textContent=day>.65?'DAYLIGHT':day>.34?'SUNSET':day>.1?'NIGHT':'DAWN';island.rotation.y=yaw;island.position.y=Math.sin(t*.8)*.14;leaves.update(dt,t);cam.lookAt(0,1,0);r.render(s,cam)}frame();
