const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d'),readout=document.querySelector('#readout');let W=960,H=540,dpr=1;
function resize(){dpr=Math.min(devicePixelRatio,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rand=(a,b)=>a+Math.random()*(b-a),lerp=(a,b,t)=>a+(b-a)*t;
class ParticlePool{constructor(size){this.free=[];this.live=[];for(let i=0;i<size;i++)this.free.push({})}spawn(props){const p=this.free.pop();if(!p)return;p.on=true;Object.assign(p,props);this.live.push(p)}clear(){while(this.live.length){const p=this.live.pop();p.on=false;this.free.push(p)}}update(dt,draw){for(let i=this.live.length-1;i>=0;i--){const p=this.live[i];p.life-=dt;if(p.life<=0){this.live.splice(i,1);this.free.push(p);continue}p.x+=(p.vx||0)*dt;p.y+=(p.vy||0)*dt;draw(p)}}}
class Animal{constructor(kind,index){this.kind=kind;this.index=index;this.x=-100-index*90;this.y=0;this.phase=Math.random()*10;this.rest=0;this.climb=0;this.base=kind==='elephant'?18:kind==='lion'?28:51;this.color=kind==='elephant'?'#79817c':kind==='lion'?'#c88842':'#d8ad57'}update(dt,wet,weather){this.phase+=dt;const active=wet?1.12:.75;let pace=this.base*active;if(this.kind==='lion'){if(this.rest>0)this.rest-=dt;else if(Math.random()<dt*.035)this.rest=rand(1.2,3.2);if(this.rest>0)pace=0;}
if(this.kind==='elephant'&&weather==='rain')pace*=.65;if(this.kind==='leopard'){if(this.climb>0)this.climb-=dt;else if(Math.random()<dt*.025)this.climb=1.8;pace*=weather==='storm'?1.35:1.08}this.x+=pace*dt;if(this.x>W+130)this.x=-160-Math.random()*180;this.y=H*.68+(this.index%3)*H*.052+Math.sin(this.phase*1.5)*2}
draw(){const x=this.x,y=this.y,scale=clamp(W/900,.58,1.25),k=this.kind==='elephant'?1.38:this.kind==='lion'?1:.72;ctx.save();ctx.translate(x,y-(this.kind==='leopard'&&this.climb>0?Math.sin(this.climb/1.8*Math.PI)*55:0));ctx.scale(scale*k,scale*k);ctx.fillStyle='rgba(49,38,28,.18)';ctx.beginPath();ctx.ellipse(0,11,30,5,0,0,7);ctx.fill();if(this.kind==='elephant')this.elephant();else if(this.kind==='lion')this.lion();else this.leopard();ctx.restore()}
lion(){ctx.fillStyle=this.color;ctx.beginPath();ctx.ellipse(0,0,25,12,0,0,7);ctx.fill();ctx.fillStyle='#77452f';ctx.beginPath();ctx.arc(19,-9,11,0,7);ctx.fill();ctx.fillStyle='#d3a04f';ctx.beginPath();ctx.arc(21,-9,7,0,7);ctx.fill();this.legs(18);ctx.strokeStyle='#75402c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-23,-2);ctx.quadraticCurveTo(-38,-10,-35,6);ctx.stroke()}
elephant(){ctx.fillStyle=this.color;ctx.beginPath();ctx.ellipse(-3,-2,29,17,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(23,-8,14,0,7);ctx.fill();ctx.fillStyle='#aab1aa';ctx.beginPath();ctx.ellipse(17,-10,12,10,0,0,7);ctx.fill();ctx.strokeStyle=this.color;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(34,-5);ctx.quadraticCurveTo(43,8,34,15);ctx.stroke();this.legs(22)}
leopard(){ctx.fillStyle=this.color;ctx.beginPath();ctx.ellipse(0,0,28,9,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(25,-6,8,0,7);ctx.fill();ctx.fillStyle='#5d4531';for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(-17+i*5,Math.sin(i)*4,1.6,0,7);ctx.fill()}this.legs(13);ctx.strokeStyle='#604128';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-27,0);ctx.quadraticCurveTo(-43,-12,-39,10);ctx.stroke()}
legs(n){ctx.strokeStyle=this.color;ctx.lineWidth=5;for(let x of[-n,-n/3,n/3,n]){ctx.beginPath();ctx.moveTo(x,5);ctx.lineTo(x-2,15);ctx.stroke()}}
}
class Savannah{constructor(){this.animals=[new Animal('lion',0),new Animal('lion',1),new Animal('elephant',0),new Animal('elephant',1),new Animal('leopard',0),new Animal('leopard',1)];this.grass=Array.from({length:100},()=>({x:Math.random(),h:rand(4,15),p:Math.random()*7}));this.clouds=Array.from({length:7},()=>({x:Math.random(),y:Math.random()*.25+.06,s:rand(.5,1.25)}))}update(dt,wet,w){this.animals.forEach(a=>a.update(dt,wet,w))}draw(t,wet,weather){const sky=wet?['#5f9caa','#c8d8bd']:['#d88955','#f3c86b'];let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,sky[0]);g.addColorStop(.62,sky[1]);g.addColorStop(.621,wet?'#728f46':'#b19042');g.addColorStop(1,wet?'#35613b':'#987436');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle=wet?'#5b7850':'#8b6e48';ctx.beginPath();ctx.moveTo(0,H*.54);for(let x=0;x<=W;x+=35)ctx.lineTo(x,H*.5+Math.sin(x*.022)*16);ctx.lineTo(W,H*.65);ctx.lineTo(0,H*.65);ctx.fill();ctx.globalAlpha=weather==='storm'?.25:.35;ctx.fillStyle='#fff2db';for(const q of this.clouds){let x=(q.x*W+t*6*q.s)%(W+160)-80,y=q.y*H;ctx.beginPath();ctx.ellipse(x,y,55*q.s,15*q.s,0,0,7);ctx.ellipse(x+40*q.s,y+4,40*q.s,12*q.s,0,0,7);ctx.fill()}ctx.globalAlpha=1;this.tree(W*.13,H*.57,wet);this.tree(W*.81,H*.57,wet);ctx.strokeStyle=wet?'#618338':'#aa8637';ctx.lineWidth=1;for(const blade of this.grass){let x=blade.x*W,y=H*.86;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.sin(t*2+blade.p)*3,y-blade.h);ctx.stroke()}this.animals.forEach(a=>a.draw())}
tree(x,y,wet){ctx.fillStyle='#62452b';ctx.fillRect(x-6,y,12,H*.22);ctx.fillStyle=wet?'#476c3d':'#67713c';for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(x+(i-2)*17,y-10-Math.abs(i-2)*8,30,15,0,0,7);ctx.fill()}}
}
class WeatherManager{constructor(animals){this.kind='sunny';this.particles=new ParticlePool(380);this.animals=animals;this.tornado={x:-80,y:0,life:0};this.flash=0;this.nextBolt=2}set(kind){this.kind=kind;this.particles.clear();this.flash=0;this.tornado.life=0;document.querySelectorAll('[data-w]').forEach(b=>b.classList.toggle('on',b.dataset.w===kind))}safeLightningX(){// choose candidates outside every live animal's horizontal safety envelope
const candidates=Array.from({length:18},(_,i)=>(i+.5)/18*W);return candidates.reduce((best,x)=>{const d=Math.min(...this.animals.map(a=>Math.abs(x-a.x)-55));return d>best.d?{x,d}:{...best}},{x:W*.5,d:-Infinity}).x}spawnWeather(dt){let count=this.kind==='heavy'?70:this.kind==='rain'?28:this.kind==='snow'?18:this.kind==='tornado'?12:0;for(let i=0;i<count*dt;i++){if(this.kind==='snow')this.particles.spawn({x:Math.random()*W,y:-5,vx:rand(-9,9),vy:rand(22,42),life:8,size:rand(1,3),type:'snow'});else if(this.kind==='tornado')this.particles.spawn({x:this.tornado.x+rand(-22,22),y:this.tornado.y+rand(-25,30),vx:rand(-18,18),vy:rand(-12,12),life:1,size:rand(1,4),type:'dust'});else this.particles.spawn({x:Math.random()*W,y:-8,vx:-rand(55,110),vy:rand(270,430),life:2,size:1,type:'rain'})}}
update(dt,t){this.spawnWeather(dt);if(this.kind==='storm'){this.nextBolt-=dt;if(this.nextBolt<=0){this.nextBolt=rand(1.6,4);this.flash=.16;this.particles.spawn({x:this.safeLightningX(),y:0,life:.16,type:'bolt'})}}this.flash=Math.max(0,this.flash-dt);if(this.kind==='tornado'){const target=this.animals.reduce((a,b)=>Math.abs(b.x-this.tornado.x)<Math.abs(a.x-this.tornado.x)?b:a);this.tornado.x+=Math.sign(target.x-this.tornado.x)*dt*24;this.tornado.y=H*.72;if(this.tornado.x>W+100||this.tornado.x<-100)this.tornado.x=W*.5;this.tornado.life=1}this.particles.update(dt,p=>this.drawParticle(p));if(this.tornado.life)this.drawTornado(t)}drawParticle(p){if(p.type==='rain'){ctx.strokeStyle=this.kind==='storm'?'#b7d8eb':'#b5d7df';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-p.vx*.025,p.y-9);ctx.stroke()}else if(p.type==='snow'){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}else if(p.type==='dust'){ctx.fillStyle='#c5a16399';ctx.fillRect(p.x,p.y,p.size,p.size)}else if(p.type==='bolt'){ctx.strokeStyle='#fff8c3';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,0);let y=0,x=p.x;while(y<H*.64){y+=rand(15,32);x+=rand(-16,16);ctx.lineTo(x,y)}ctx.stroke()}}drawTornado(t){let x=this.tornado.x,y=this.tornado.y;ctx.save();ctx.globalAlpha=.5;ctx.strokeStyle='#876a54';for(let i=0;i<6;i++){ctx.lineWidth=3+i;ctx.beginPath();ctx.ellipse(x+Math.sin(t*8+i)*10,y-i*13,9+i*4,3,0,0,7);ctx.stroke()}ctx.restore()}}
const eco=new Savannah(),weather=new WeatherManager(eco.animals);let wet=true,seasonTimer=0,last=performance.now();
function setSeason(value){wet=value;seasonTimer=0;document.querySelector('#season').textContent=wet?'WET SEASON':'DRY SEASON'}document.querySelector('#season').onclick=()=>setSeason(!wet);document.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>weather.set(b.dataset.w));
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;requestAnimationFrame(loop);seasonTimer+=dt;if(seasonTimer>60)setSeason(!wet);eco.update(dt,wet,weather.kind);eco.draw(now/1000,wet,weather.kind);if(weather.kind==='rain'||weather.kind==='heavy'){ctx.fillStyle='rgba(78,126,135,.22)';ctx.beginPath();ctx.ellipse(W*.5,H*.83,W*.38,12,0,0,7);ctx.fill()}weather.update(dt,now/1000);if(weather.flash){ctx.fillStyle=`rgba(255,255,230,${weather.flash*2})`;ctx.fillRect(0,0,W,H)}readout.textContent=`${weather.kind.toUpperCase()} · ${wet?'WET':'DRY'} · ${weather.particles.live.length} P`;}
requestAnimationFrame(loop);
